public enum VOICE_TYPE
{
    ATTACK,
    ROGER_THAT,
    AFFIRMATIVE,
    BOMB,
    YES_SIR,
    FIGHTER,
    TANK,
    MENU_BACKGROUND,
    GAME_BACKGROUND,
}

public enum CITY_CLASS : byte
{
    CITY = 1,
    REGION_CAPITAL = 2,
    COUNTRY_CAPITAL = 4
}

public enum DIVISION_TYPE
{
    ARMORED_DIVISION = 1,
    MECHANIZED_INFANTRY_DIVISION = 2,
    MOTORIZED_INFANTRY_DIVISION = 3,

    BOMBER_DIVISION = 4,
    AIR_DIVISION = 5,

    SUBMARINE_DIVISION = 6,
    DESTROYER_DIVISION = 7,
    CARRIER_DIVISION = 8
}

public enum BUILDING_TYPE
{
    NONE,
    AIRPORT,
    MILITARY_FACTORY,
    HOSPITAL,
    UNIVERSITY,
    FACTORY,
    MINERAL_FACTORY,
    OIL_RAFINERY,
    NUCLEAR_FACILITY,
    TRADE_PORT,
    GARRISON,
    DOCKYARD,
    MILITARY_BASE
}

public enum WEAPON_TYPE
{
    NONE,
    RIFLE,
    TANK,
    ARMORED_VEHICLE,
    TOWED_ARTILLERY,
    SELF_PROPELLED_ARTILLERY,
    ROCKET_PROJECTOR,
    LASER_GUN,

    FIGHTER,
    HELICOPTER,
    DRONE,

    COASTAL_PATROL,
    CORVETTE,
    FRIGATE,
    SUBMARINE,
    DESTROYER,
    AIRCRAFT_CARRIER,

    ICBM,
    NEUTRON_BOMB,
    ANTI_MATTER_BOMB
}

public enum MILITARY_FORCES_TYPE
{
    LAND_FORCES = 1,
    AIR_FORCES = 2,
    NAVAL_FORCES = 3
}

public enum POLICY_TYPE
{
    NONE = 0,
    ECONOMY = 1,
    POPULATION = 2,
    MILITARY = 3,
    HEALTH = 4,
    CONSTRUCTION = 5,
    EDUCATION = 6,
    RELIGION = 7,
    DIPLOMACY = 8
}